### ISSUE TITLE
Why alpha is 500?

### ISSUE THREAD

**Issue by Baran-phys** [rafaelbidese/LOGAN#8]
In the paper, the value of alpha after the hyperparameter search is stated to have the best value of 0.9 for both DCGAN and BigGan. I wonder why the value of alpha is set to 500 as default? does that even make sense?

**Comment by rafaelbidese** [comment]
@Hosein47 thank you for the question. No, it seems to me that it does not make sense to use such value nor leave it as default. That's probably something I forgot to change back when I was testing with extreme values (kind of an ablation test). 

If you use a different NN architecture and/or dataset I would do my own hyperparameter search - maybe, guided by their values. Otherwise, if you are trying to replicate the results, I would suggest that you use the values that the authors used. BTW, I don't remember seeing the hyperparameter search portion of the paper when I studied it, that would've helped my studies.

One thing to notice is that this method does not implement the use of the hyperparameter _c_, which is the portion of _z_ being optimized, it always optimize all _z_ (c=1, 100%). Though, it shouldn't be a lot more work to implement that.

Maybe, I could change it to a reasonable value to avoid further misunderstandings.

**Comment by Baran-phys** [comment]
Thanks for the answer. Yeah, I am using LOGAN for an entirely different dataset and architecture.
I think the hyperparameter "norm=1000" that you introduced for ngd, it seems that in fact, the value of alpha is equal to 0.5 (500/1000) in your implementation. Am I right?

**Comment by rafaelbidese** [comment]
The norm parameter that I introduced was a procedure mentioned in a section that is no longer in the paper. They mentioned that they normalized the _z_. It seems like the normalization process is now better explained in the last section of the v2 paper. But yes, if I had worked out the equation, that would be the result.

Here is the v1 of the paper that I used as a reference: https://arxiv.org/pdf/1912.00953v1.pdf
Appendix/Section E/Second paragraph is where they mentioned the regularization weight ||z||. Since it was not very clear to me how that would be implemented, I used the "norm" hyperparameter. And again the value is probably left over from my evaluation of the effect of the parameters.
